[tool.poetry]
name = "pysnake"
version = "0.1.0"
description = ""
authors = ["Jochen Parmentier <jochen.parmentier@external.atlascopco.com>"]

[tool.poetry.dependencies]
python = "^3.9"
pygame = "2.0.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
